name: Python Package using Pip

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Uvicorn server
      env:
        DEBUG: "True"
        DATABASE_URL: postgresql://postgres:nNAWAB%4064293975@db.wtycdayayaewgrsputpm.supabase.co:5432/postgres
        SECRET_KEY: your-secret-key-for-jwt
        ACCESS_TOKEN_EXPIRE_MINUTES: 30
        RAZORPAY_KEY_ID: your-razorpay-key-id
        RAZORPAY_KEY_SECRET: your-razorpay-key-secret
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USERNAME: your-email@gmail.com
        SMTP_PASSWORD: your-email-password
        EMAIL_FROM: noreply@globalpooja.com
        OTP_SECRET_KEY: your-otp-secret-key
        OTP_EXPIRE_SECONDS: 300
      run: |
        pip install uvicorn
        uvicorn app.main:app --host 0.0.0.0 --port 8000
